#use 5.014;
use strict;
use warnings;

#Input string
my $dna = "GCGAGTCTAAGTCCGATTTATCTGCGATCTGTGGTTGGGACTCTCAGGCTCCCACACGAATGAATATCTATCCAGGGGTGTCATGGGTTAAGGGCCAGCGGGAAAGCACTGTTCTTTGTACTCACAACCCCTTTCCGAAGCATTGCTCCTTGTATTCACAACCGAGGTGATTTGTCTCATCCGGCAGACCACGCCGATGGCACATTGCCTTCATAGCAGGGTAATTGGAAACGGGATGCACGTAGAAATCTTACCGCCAGTCCGAGCGACATGTCACCCGAATTTTCACAAGTGTAAAGCATTGCTCCTTGTACTCACAGCCTCAAGCGATGGTTCAGCCCAGCTAATCCAAGAGGCATCGCTTGTTGCAGTCGACGAAGCCAGGGTACTCTATGGCCCTTAGCAGCCTTGGTTGACTGCACGATGTCTTCGTACCCTGCAAAAGGCTTGCATACCTGTCGGGGCTATGGGCTCTCTGGGGCAGACATGAGACACAAAGGTGTGTTTATAACCCTCGGTCAATATTGAGCGTCCACGACATCGGCGTCCCGTTCGTCATTGCTTTTCATGGCTGCGCTGCGAGTCCTGTGAGTGCTATTAGGGGTCACCGTTTGGACACGTATTATGCCTGGAACGCAATACGCAGAGTGTGTGTCTCCTACTTGAACTGCCTCGGAGGGCTCACTGGTCCGTCTTCGACCATTCCAAGTTGTTGGTAGGTGCAAAGGTGAAGTAGATTCAATAAAAACAGGAGGGGCAGCTGGGTGTTTACACGTCTACGCACGGCAATCGCCTGATGATAAGACCACCCACTCACAAGTTTCGGGCAGCAAGTTGTACACTTGATGCACATCTCCACCTTGTACGGTAAAGTTGGACCGCCAAGTCCTGCGGAAACTAGACATGAGTGATAAGGGTAGCGATTTTACCAAATGAGATTACAGCACACTGAAACTGACAAACTTCGTCGATTTCAAGCGGTCTAGAGTTGTAATCAATACAGCAGAGAGTATGGCCCCGGACTGTTACACACAGGGCCCGAGCCCTCCGTTATCCTGCTATCTCTAGAATAGTGAGTACGGCGAGCCCACAAGGTGTAGATACTGATAACAGGTTGCGAATATAAGGAACAGTGCTTCCTGCTTGCACAGGATAGTAGGACGATATTCTAGTTTCTGGCTGCTAAGGTCTAATCAACACAACACGCGTTCCGCAATACGCCGTGGGGTGCCAAGTCACTACCTAGGCCTTGCCGTATTCTCCAACTGGACTGGTGGACATTGTCCTGATTGAACTCATGTCGCACCTTAAATGGTGGGCTGCGCCATCCTTATGTCATTGAATGATTGTGGAGTTCAACTATGTTCGACTCGGGCCAATACATAATCGTTTGGTCACGCTTCACGAGTCCGAACCGGCATCCAGGGTGCCGACACTGCCGGGCCACGCTCTTAACGGCCTACAAGAAACGCCAAGCGCCTACACCACCAACAGGAGCGTTGCAGAATCCTCTACTAGAATTGGTTTACAGGCACACGGCACCGCCGCCGTGTTATCGATGTGCAATTTTCAGTAGATAGCACCATGTTCCACCCTAATCAAAATGGGATGTATTAGGACGAATTATAGATTTGCGGTCTGTATAGGGGCCTGACTAGGTACAGGTGATAATGTGTGTCTGCAATAGAGACATTGTCCGTGTGCATAAATCAAGTCAACAGCAAAATTCAGCCCTATCATCCCCAGGGTCCACTCATGCGCATGCCGTGGCTCCCGTATCATAAAATCCTCTGCCCAAATACGAACCATTCTTGCCATAGGCGATTAAAGAGGGCTCTTGCCTACTAAGACGTTGCAAGGCTTGGGGAAGAGTGAACCCTCTTCTCTCAAGGATTAACCTTGAGAGGTCTTCCGGTCCGCCATGCATTGCGGCTCAAGGCTGGATGTGAATATAAAGAGCAGTGTTTTCGCGATGCCACGGCTAACAGATGGGTGTGGCTACAACAGTAGAAGAACAAGCGAATGCGGTATAAAAGGCTGAATCTGGGTCAGCCTCATGACCGAAACACTGTTCTTTGTATTCGCACCCGGTAAGCTAATTGGCCATCAATACCCAGCCAGCAGTTTACCTAGATTGACTGAATCATCGCTTCTCATATGCAAGTCGAGCCTCTTGCCATCAGGACGCGCTAAGGCGGTACATCACGTGACGAGGTTATATTGAGACCACGCTCAATATCCGACGACTGACAAGTGGGGGCCCCCTTTTCAGATCTTATGACAACTTTCACAGATAAGAGGGGCCCCGGTGTCTCAATGTGCAGCTTTAAACTTACAAAACAATCGGCAGATGACTCGTCCCCAAGAGCGGTTTTCGCAAATTTGCCCATGACGATTCACATACCTGCGATGAGCCGCCCTACGTAGCGGGTCAGATTCACTCAACTAAAGAGACTCCTGAGAAGGATTGAATACGTGATCAAGAACACGAAACACTGTTCCTTATATTCACACCCGTCACAAAGAGGCCATGCCGGTTTACGCGGTAAAACTAGCTATGATTACGACTTATACTCTAACCACTAACGAACTAGTCTCGTGGATGTGAATACAAAGAGCAATGCTTCTTTCATGGAACCAGGTCGCCTATCAACAGTGATGACCTAGCGGCAGAGACCCGTATACATCCGGCTGCTGTGCACTAAAAATCAGATGAATCTCTTTCGTCATGTCTCTTAGAGTGAGTCATGCCCTTCTGGATCCACCCCCACACCCCCATGAAACATTGCTCCTTGTACTCGCACCCACGTCCTCATAACACTTCTAGTAACACGCAACTTTCCACTGTCTTTCGGTGTCTTAACCATTGGTCCTGACCCTTTCCTCGCCTTAGGGTTAACCGGGCGGCTGCGAATATAAGGAGCAGTGCTTCTCAACCCACGTCCGCGAGAGGCAGCAGAAAATCAGGATCCCTGTCGTTGGATGTCCGGACTGTTCATAACATGTACGGGTCGTCCTCAAAAACATTGCTCTTTGTACTCGCACCCGTCCCCGCCCGCCTTGCAAGTAGGGCTCAACTCCTTGCCTTGCAGTTCAGGTTATATATCAACTCGTTAGCAGTGGCGCAATCCCGAGTTATTCCACCGAATTTTTTGGCCGTAATCATCATGGGTAGGCTTAGGTCGAGCACCGGTACGGAATCCATGTACGACCATATAGGTTAGAAGTTTCCTGACCGTTTGGCTAACAATTAATAACGGAGGATCGTCATTCTGATCTCATGAACGGTTTCGATCAATCGTGTACTAACATGCTGACCACGAATCGGGTGTCGCATCGGCGAGGTCTCTCCAAGCCACGAGCATGGGGGTGACCCGGCCGCCAATACTCGGGGAATAACGTATCCGAGAGGATCTTGATGACCATTTCGCGGCCTAATGTAAAGGGCAACGATCGCCCATTACTGACGTAAAGGGCTGTGTATCCTTGCAAGTCACGCCTCGTCACGGGAGGCATATGTGGGAGAGCGTGTCTCTAAGAAGAATATGAATAGAGCCGCAATGTAAGTCTCTGGGGAGTCGCCTCAATGGGGCACGAAGCTATGCTTCGAGAAACATGCAGAATAGCATGAAGACTCAGCCTTTGCTTTTACATAATATCCACCGTATCGGCTTTGCCGTCGATTAACAGAGCGTCTGTCACACACTCCCCACTAAGTCTTGAGGGATGCCAATGTGTGAAAACAGTGTAGTAATCACACACAGGGGCTTCGTCAATGTGAGCGACATAATTGAAGTTAATCACCACCATTGTAGCGTTAATATATAGATAGCCTATATTCCGTTAGCTTCCGAGCCCCTTTTAGACAGGAACCACGACTTATCACAGACGGAAGTCTGTGCGCCATATGGACAGACTCCCCAAAGCTGAAGGACTGAAATCATGCGCGGCGCAACCCCGCCGGGGAGACCCGTAGGCCTTTTTTTGATGGTGGCCGGAAACATTGCTCTTTATATTCGCAACCAAAAGAGCTCTCAAAAGCACTGTTCTTTGTATTCACATCCGTCTAAGTGCCACTTTGTGGGCCCATATGAACCGACTTGTCTCACGTTATACTTACTTCGTTTCCAACCAACATTACGTCGATGAAGTAAGCAGCCAAGACACCAATAAGCTACCCAAACATGTAAGAGACCCAGTTCTTTTGTTCCGAATCAAGTGTCGCCGAGCCTAATAGGTAAGCGTCGACGACGTGCACGGAGTCGCTCTCCATCAGCCTTGGGATGACATTTTATATCTTGCAAACTGGAGGTGCATACATGGCGGAACAATAGGGATTAAATGCTAGCAGCTTAGCCGGCCGAACACCCAGGCCCGGGAACGGGTCAAGTGTTGTCCTCGTTTTCATTACTGGAGAATAAGCACCGGGGACAATGTATTTTCGCAACCACTGGCAGGAGGGTTGCATCAGTGAGCGATAGGGATGCTACAGAGCTTACCGTAGAGAATCTAAAGGCATCACAGCCGTGGACCAGCTCTGAGCATTTCAGTAATCCACTTTCGACGGATTCAACAAGAGAGACGCTGTCCGGGTTCATTGCGGCATCTCATGATTCATAGGGCTTCCATGCTCTGCCGTCTAAACATGGATATCTACGCCCGTAGCAGACGCAGTACTCCTCGGTTGTGCTTGGAGGTGCTTCTGTATCCTTCGCGTAAACAGCAGCCCAGGGAATAAGATATGTACATCCCCGGACCCAGAGGACGTCATATTGCTGCGTATCGGTACTGTATTGGATTGCTCGGTCTAGCGTGAGAGAGCTTGGGGATTTGATTGCACGGTTGTAAGGCATAGTAGGCAGGGCTGTCTAACTTTCGAAACCCGCCGCCGTCGGCTGAATAAGGCTAGTGGGTAGTGGGGCGGCTCACCCCTTCAGTTACAAATCCTAAAGGCCGCGAAGCTCGCGCTAGGCTTAAGGGTCTGGTCGCCTTCGGATCCCAGGAATAATGCCCTGGAACTGTGGCGGTTTTCAAACGTATTGTATTTTTCGGGGTCACAGACGCAAGCCCCCCTGGCTTAAATGCCCTGTCCTTCGTACGGCTGTGCTTCGCCAGATGAGGGGGTAACCACCGATAGATGAACGTCGAGCGCCACCAATAATAGACCAACGACCTTGATAGCCAAACACGTCTAAGTGGCTGCCTCCCGATTATCAGCGCTTTGCTCAAGACCACGTAAAATAGTAAGGATTGTACGGAAACCGTTCGGTATCTTTGACATACTGATCATACGGAGGCACTATCCTCCCAAATGATGAACCGTCGACGCCGTAGAACAGAACGGATCGAAGGATGTCCGACTTATGACTTCGGTAGTTACTAGGCAGCTATCGGGGGCTGAGGTACTCCAGCTTTCCACGGTCTTAATTTAGTCGGGCCGACGCGACATAATCATAGGCCCCCGAATTGCCGCGATGGTTAACCGAGGTCATGAGTCTCAGTATGTCTCTCTCGCCAGGCTCTCTATAGGTATGGTAAGTAGTCGACGACCGAAAGGAAAACCGGACCACGCTATTCTCTTTTAATGGTGAACAACAAAGGGTGCAGTCCCGGCACGGGGCATATATGAATCAGCTGCGACGCCGCCGTCCTAATACGCGAGTACGACTCTACCAGGGTCATTTGACTAGTATATCGACTGTTCGTTGGCATTATAGTTCAAATCTTTAACCGTTCGTCGAGGGGATCTGGGCCTTTCGGATAAAGTTTTGAACGGCTTGCACACAGCCAAGTTGGTAGGTGCCGAAATTGACTAACGCCCGCGAGCTCCCGGAATCCACGTTCTTTCCAGGTAGCAGTGAGAGCGCTACCGTGTACTCAGAGCTGACGGCTTGTAGTGGTGTTCGCAGTTGTACTTCCAATGTGGCCACATTACTACGCAGCTCGCAAAACATTAGAGTGGGCGCTTAAGAGTTCCGTTCCAAATCAGCAATCGTATTGTCGACCGACTTCTTTATCTAGAGATCCCTGTTTGTATCAACATTCATCATAAACTACGCCTCCGACTCTTTACGGAATGGTGGTCCGTGGTGCCAGAGTTCTAAAGGCGAATCGCCTTCTTGTGCCCAAGTTCTCGAGCCTGTCCAGCACGGCGGCTCTCAGAATCATCTGCATTCAGATTCGCCAGTGGGAAAGAACCACCCGCCATACGGTAGTATAACACTGCAATTTCCTCTCACGGTATGCTTGTTTCGTAAGATCAAGCGTGGAGCAGTCGGGTCACTAACGTACTAAAACACTGCTCTTTATACTCACAACCTGAAAAGGAGATAAGTTCTAGACAAGCGTTTCCCTCATGTGGTAGGCTACATCCAGGGCGGCTTTCAGGAGCATGTGTAACATGAGACTATCTGTGGTCATGAGACGCAAGAAAGTAACCGGGTGTGAATATAAAGAGCAGTGCTTTTAACCCGTATTACTTGTGTGCCAGGCGCGAACTATCACGATTTAGGGGCTGATCCGGAGCATACATCGCCCAGCTACCTTATGGTCCACCCGCATGCTGATTAGCTAATAAGGGCAGTCCAGCCACTTGACCCTAGCCAGCACATGAAATACTGGTACTTGCGCTACAGGCCACTACATTGGCTTAGCCACGGTATATTATGTGGTTCACATAATGGCATAGGGATTGGGCTGCGAATACAAGGAGCAGTGCTTCACGTTTCCCGAGCAGTTGTATGCGCAGGCTCTAGGCCAAAGCACTGCTCTTTGTACTCACACCCGGACACTAACATTCGGGCTGAGAGGGAGCTGAACCGGAAAAGCATTGTTCTTTGTACTCGCATCCGCTAAGTCTATGCCGGCGTTTCGTGCGCCGATTCACCCAACCGACTCCTAGGCGCTATTGGAACCCGTGAATTGAGAGTACAATTCCGATACTCTGACTCAAACTTTCCCGCCAACATTAGCCAAACGAACATGACTAGGTCCCTAAGTCCCGGTAATCCAGCAGCTCAAGACGTAAAGATATTGGGCTGAACCGGCTGATACACGAGGAACGCGGCTCTAAGGCTCGAGTGGGACCGGAAACACCTTGTCAACACGATCTATTTCCCTCTAGACTTCAGAGGTGTGTCTTATCACTAGCCTGCCGGGGTAGCGGTCATTGCAAACAAGATTGCGAAAAGAGGGTTTACATATTGGTGAGGGCCTAGTAAGACTGTTGTGTTTAAGCGACCCTAATCGTTATACGTCCAAGCGTCCCCCGCTTCACCAAGTAACTAAAACTCCACGCGGTCGATTTTGATAGCGCGAAACGTCTCACCCAGAACCATGGTCCGGCGCATCTGCTCGATTTTCAGGTATCGCGTCACGCAATCGCAAGCAGGAAACAGCACCTCTAGGCGGTGGCAATACTCATTTCTTGTCGGTGACTTATATCCGGTAGCAGTGGTTGATACTCAGGGCACGTCTTGCTCACTCAGATGTAAATAGATTAGCTTCGGCATCCTGCCGCCGGAGACAAAGATCTACATGCGCAGATTGACCATTGATAAAGTAGCGCTAGCAGTCAAACGAGTTTTGAGGTTGACCCGGTCAATTTCCGACCTAACGAAATCCTCATCCAAACTGACCCTGAGGACTTTATTGGATCTCACCGTACCATGTAGTCAGGTTAAGTTACTCGCTGCGTCCGACTATTTCCCCCTCACGTCCGACGACGTTTGTGCCCAGTTACCAGGTATAACGATGCAAAGGCGGGATACGAACAACGATATCTGTCTTAACATGTTCTGCACACGGGATAGGCTTTATGTGCAGGGTCGTCCATATCGTGGTTCACCATGGTGGACCTCTTATCCGGTGTGCTCGGAAAGTGTTGCACGCCTGCGGCCGTCGATAGCATCACATGTAATGAGGAGGGTTTACGTTACTCGGCGAACGACTTAAACTTGGGCAAAACGCGATCTTCCTTAAGAGTACAGGCCCCGCCACCCTTTATCGATTAATATGGCTCCGACCGGGTAACAAACTACAGGATGTGAGTACAAGGAGCAATGTTTTCACTGCTCTTTATATTCGCAACC";#"TCTGATTCTCGCTCCTTTTCTCGTCTTACCAGGCCCTCCACTGAAGAGGGTCGGCCCCTTGCACCGCAACTTAGTGTCTTAGCAAGCCCCTAATCTCCGCTGCGACGTATTGCGGCTGGAACATCTAGCCGTGAAGTCGCTTGACTCTGAAGGTCCCGCCAATGCACCTATTGTTCTTCGTTACACCCCATCCCTTCGGCGGATTGCCAAAACTTGGTTACTACTCGTACCTCAGCCGATCGTCATGAAAGGGGGAAACCATGTACAGAGCCCATATTCACACCTGGGGTCGAAATAACTTGTGCAAATTATCGCATAGACCGCGACTTTATATACGGCGTCAGATCAGCATTACATTGTAACAAATGCCAAGGAAAACCTTGGAGCTGTGTATACGGAGGAAAACGCGTCAGCAGATTTGAATCATTATCATCCCTTAGCAGGGTAGCTACCATAGACCCGCGGCCCGTGCGCGTCGGACTCGCTTAGTCTCACGCAGGCGTGACGGTTATGGACCTGCGCCCCTTTTGTAGTCATAGTATTAACTACATTATCTTTGGGACTGGTGCATTGGGGCTGTTTACACGGAGGAGAATGCTAGTACAACCTTTTCCGCTGGCAGAGGTCAGTGTCAGGTAACGAAGATTGACACAGATTGAGTTTAATCGTAGCCCTTACTGAGCTCGGCCTCTACGTAGCTTTACCCAGCGGAGCGGGAATCGCATCGGTGGATGATTCCATAATTTGGTATGTGGTCACCTCTGATAAAAGACTAATTAGTGGCGAAATAACAGGTCAGCAGCCTATTGGGAAGGGGCGTCTCGCAATAGTCCAACCCTCCGCTAAGTTGGGATTCCTGCCTTGTGCACTTGATCACTGGATATTATCTGGCATAAATGGGCCTTGAACGTCCTAACGTACTTCGCCCATTTACCTCGGATTATGGCAGAGACGCTGTCAGCCTATGGCTAAGGCAGACACCTGGTTATCCCCGGATGCACGTACTGGTTTCTCCTGTCACGACGGATCAGATTGCAGGCGGTATTCGATGTAGTCGAGAGTCGATAATGCTTAAGGTGAATTTATCACCAAGATTCCTCCGAAGTTGAAGTATGACGCATTTTCCTCCGTGTACACAGCCCCGATCGAACAGTGGGGGTCGTCCACCTAGCCGAAGGCTACCGCGCCAGCCCCCTTATCCCCGCAACAGAACAGTTCGAGGTTTTTGCATTCCAAGAGCCTGACATTTAACCTCCTGGCTGTAGCTTAGTAGGAGCAGCTATTACATTTATAAACCATTGCGCCCAATATCCTCGTCGAGGCGTACATATGCCCCACCGGGACGGAAAATAGCCATGACTAACACGGCTGCGTAGATCCAAACCGTCGGCTTTTCGGACCATACTGGCATTTTCTTCGGTGTAGACGGCTCCGCCGCAGATGGAAAAGATGGTTCATCAATGTCAGCACCAGGCAAGCACTAGACATCGAGTACGCACGATTGGGGTGAAGATAATTACCACTCTAAAGGATATCTAAGGTTTAGTAAATTTCGATCGCTTACGTCTTCTACAAGTCCGGTCCCAACACTCTGGAGATAAATTTGTCAACTTAGTATCCTCGAGGTGAGCTGGGGTACGGCAACTGGATAACACATGCACGGGCGGTTACTGTGGAATACTATCCGGTCATGGGCAGTTATGGATTCCTGAAGCCGGTGATAGTAGGATACAGACCCTGCTGCGACCGAGTCGTATCTTGCACTTGCGTAGCCTATTGTTGCGTTCTCACGCAACAAATATTTTTACGTTGGCCCAATCCAGGGCGTATTTCGTGGCGCGAGTGTAGGTATCATTTTGCATACCAATGGCTACCGAAGCATTCCGAATCCACTAGGATTTAGCGGGTAAAACCTGGAATAATGGTTTTTGTATGAACCATGTGCAACTGGTAGTACAGGGTAGGAACAAATGACGTCTCTGTTGCCTCAACGCCTGAAACACCCATTTAGGAAGTTCCCTCCTGGAATCCCGAAGAAATTACAGTCAATGCACCCGCGTCGCGCAAGTAACAAAGTCTCCAAATCTTGGGTCCTATTGATTAATTGGGTCCAGCGCTTTGGCCAGTTTCGTAGGAGAGACGAACGAACCCATCCCGACGTCCGAAGTTATGCTGGTGGAGGCTAAATGGTACGCGCCTTTTGGTAATACGGTCCCCGCAATTACGAAGAGAAAGACCCATGACCTCGGATACAAATTTTTGGTGATTCAAAGTCACGAACATAAAGCTGACTCACAATTCATTCATCGATGGTGCCCCGGGGGCAGTCTATACCGAAGAAAATGCGTCGTGCGTACGACCGCTTAAAGACGTTGATCAACGTGAAGACCAATCAGTTTTTCCGGAAGGGGGTCTGAACGTGATGCGCGGAGACATCCCCTTGCTATTTTTTAACGCCAATACATGGGCGACGTTAATGCGATTGCAGCCAGAACGGAACTGCCCACATATGCTACAAGGAGACTTAAGTTGTAGAATAACTTAGTCAGATACGATCCGACATTCCGTGCCTTAATGTTGTAGCCTATCTCGGGCGGGATAACACGCGACGCTAGCTTTCGCGATTCATTACCCCGAGAACGAAATAGTATCAGGGGGCACTTCTGTTTACTTAATTTCTTGAGTAACATCCCAGTGATTGCCATGGTTCGGGCTCGAAGGATTAGGATGTCATACAACTCTTTTTGGATATATCGCTGAAGCGCCGCAATCTCCCCAGTCGGGAACCTTGCGAGGTAACACCCTTGATTTCTAGTTTAGAATCTAGCGCCAATTACCAGGAATCACTAAAGTTGCAATTACTGAGAACGGCGTGAGTCACTACCGCAACGCCCTGATGCGTGATAGAGAAAGTTGTCGCACTCGGTTAGTCGGGGCTCAAAACGTACAAAAGCTATCCGCAGCCTCACTCACCTAGCCTTTGGGAGGTTTACTGCCGTAGTGCCGTTCCTAACGTACATACACTGGATGCAGTATCCTCAGCCTTTCCTGAATGGGCCTGCCGGTCCCACACTGGTTGGCTACAATGCTCTCCGTAAACTGTAGGTAAGTGGCTTACACTGTGTGGGTGACTTCTCAGAGTCATTCGGTTAAGGTCTCATGCAGTTATTGGTAGGTGACCGAATACGAGTCTGTGGACCGGACCCCAATCTTTTCAGGCGCAGCTGAACCGACTGAGAACTCGAAAACTTACGTCTCGGGGAGCGTAACGGAGGAAGTCACGTAATGTCGGCCGGGCGGACGAGGAACCTTGGTGTCTATATAATAGATATCAGAACGCCAAGTGGATGACCGTCACCTCCCGATCTCTATCGGTGGGACAAGATATAATAGATTACGAACAAACAACCCTGACCGGGCATTGATGCATTCTCTTCTGTATAAACCGCGCCAGAAATACGAAGTTCTCTGTAATAGATGAACTATTCCGCGCTTGATAGCAACCTTATCCCTCTCTAGGGCTAACTCCTCCTTGCAATGGTAAAAGTCTCATGCTTAGCCCACGTCCCTTCCACGTGGGTCTGACGGCTTAGTGCTGGACTGTGTTAATAACAAGCCGAGCTATGGAAGCCTTATCTTTTAGGCGTCGTCGCATCTACAGGGCGCGACATCTACACTGCTCTGACAAATGGTGCTGGAATGCTGGGACCAATAGGGTCATATACCCCGCCTGCATACGCTGGATTTGAAGCCGGTATAGTAGTGCAAGCAGATAGTCTCTTAGGACCTGGTCCACTAGAATTATTATTATCCACAGTGGAAAGGGGGGACTGGTCGTGAGGCATTCTCCTCCGTATAAACTGCACCGCGCATTTTTTAGGAGCGCCAAACAATATCGGAATCTTGAGGGCCACGCGATTGGAGCCGTGTACACAGAAGAAAATGCGAGCTTCTAGTAGCTCAAAGTAAACTAGCGGCATTTGACAATTGCACGCTAGATTGACCCTACGACGCATTTTCTTCGGTATAGACTGCCCCCCGTGCTGTACGCTAATGGAAGCATTCTTCCCGGGTACGTACTTAGCGCTGGTCAATAATGCTGGGTACCGACAACTTCGGTCCCAGAGCGATAACTTGTGCACTGATGAGGTAGCTCGGTGTTTCCGAGAACACGATCGCGGTGTTAGTTCGACTCTCAAACTCCGCCTTATCATTTCGCCGCCCTCTCTGTGGATATGATTCTATACCGTTGCGGAGTGCAGGCGACCACAATAGCGCTGAGAGCCCAGCGTATACGGTGAGAGGCCCATTCGCCTAATACCAGCCCACATAGCCCGGAGCAGTCAGAGTAGTATCCCTCTAGGTAGATGGGACTCAGCCTAACTGGGTAGGGGTACTCTCCCTACCGATCCGAGGTCTCTGTCGTCTCTTAAATATACGGTCGCAGCCAACCGTATTATACGGCGAAGATTAGATTGTTTCAAGAGATGTGCAACTGTTGATCTGAATCGATGCTGGGCGCCTTTGCTGGGTCCCCCATCGCCTCGAATTCGAGCAAAGCTACGCTCCTGCAGGCGCTGCTGGCGTTTTCTTCCGTGTAGACGGCACCCGTATCCTTGGCGCCCCGTGAAGATCCGAGGTTGTTTTAACGACTGGCACGCACCATACGCCAGGTACTTGCATTTTCTTCGGTGTATACAGCTCCCGTAACCACAAAGTCATAAGATCAACACTAATTAAACGATTCATAGAAGCTGCGCGAAAGGCACGCAACATGACTGCTGCAGCCTGCTTTACAACCGCTACGTGATTGGACCGTGCTCACTAGCTGACCATCGACAAGGCCAAGCAGAATGGGCATAGATAGCTTATGAATAGGCCTGACCGGGGAGCGGTCTATACGGAGGAGAATGCTTCATACGGACACCAATCCTCGTGAGCACACGATACGGATACTACTGGAAGATTACTGCGGAGTCGTGCAAGGTAAGGCTAATCATATAGAGATAGCGCGCAGCGAGTAGAAATATGTGAAAGATACATACCCGGCGCTTGGTATGTCGCAGCCCGGCCTATCCCGGACTAAGTCCACCGCCCGATCTATACTAGCGCTGATCAGAGGTACAGTATTTGCGCTTGCCTGCTACACTAGAGACGCCCAGATTCGCTGTATTCATTATCCCTGGCAACACCGCTGTCTAGGTATCGATGTAGGTATCCTTGTCGAAGCCGATCATATTCCTGTGGCTTAAAGCCGCAATCAAGATCATAAAGGTCACCCTTCGTGGCCAACTTTTGCGTATTAACAACACTTCGGGTGTCCAAGGATCCGGCGACGCAGAAGAGAGTTTCCTGAGACGTAAGATACAGATCCCCGTCGAGCGCCTAGAACTTGCCCATCGTATTATCATCCTCAGAACTTTGCAAACCTAAGATTTATAGGGGGGGGTTGAAACTGGTAGACATAGTTGTCTAAATCGGGGTCGACGTGACGTGTATGCGGATTAGGCCTCTCCGTGTTCCTAGTCACCGCGATGCCCGAGGATAATATATTTTCGAGCACATTGCAAGGTTTCTTCTGGTAATCAAAACTAGGGCAAATCACCGATACTTCTGGTTTGTTTGGCTACCATTTGCTACGACGGCAAGGCAAAGGAGCCTCCGGAGCTAGGCGAAAGGGGTGTAAGAGCCTTCCATCTCCGTAGGTTACAAGTGCTCGGCCGGCCAGGTTATAAATGCCCATTGCTAACTGCACAGATATTGTAATGCATGCTGTTGCCCTTCTGATAGACTAACGGCTGAGTCTTAACACATGTACCAGGAGGCTCGCCGTCACGGTTACACTACTAGCAAAGCTAGGCGTCACTCGCGCGGGACCGGTCCGCCTGGTGTGCACGCTACTAATCACGCACTTGTCTCATCGGATGTTGTCGAAGGTTTCCCCTGTTGAACCCCACAAAAAGCGCAACTTGGCCTCCGTTCATTATGCATCCCTTCGTTGTTACCAGCGGAGACGCGTTTTCCTCTGTGTACACCGCACCTACGGTTCTAATTTGGTGTGCGAGCAGTCATCGAGGGGCCCTGCCCCAAGCCCTACACAGGAACAACTGAATATCCACACAAAAGTAGTAAGTCTGCATTAAGATTCAGTCCTGTTTACACCCTAGTGATACGCCCCTAGGGTGAGGCCCGGGTTACCTTATGCATATTAAATCATGGGTGACGCGTTAACCAGCCTACGTGTCTAGTTCGGCCGAGTCAAGGGGAACGACGCGTAGAGACGGTTATTATACAGTCCGCAATGACTCTGCTGGTTACCGAATGCTCCTCGTGAGATAGCGTTGCGTTTGGGATCTGTCAGGCGGAAGTGGCGTATCAACTGACCGGTGCGGTTGGAGCTGTCTACACCGAAGAAAACGCCTCTAAGCAGTTGCCATGCGGAAATCTGCGGCTTTCATAGCTCAAGTGGGGACTGGCGTTCTCTTCGGTATAAACAGCCCCCCCGAGCACTCCTGGCTGTCTTGGGCGAGGTATTCCACCCTTCGGAGGCGATGCAGCGTCGACAATTTCAGACCGCCAGGAACAATGTACGCTGGGTGCGCTTAAGTTATGGTGTGTAAGGTACACAACCCACGCTAAAGTCCCGGACGGGGGCTAGCCGGTTTGCCCCGCTGTGTTGGGGTAGATTAATGCAGATAAATCACATGTCTGAGTGTTGCGCAATGATATACCAGGACTCCATAAGGCACTAAATCAGTAACTAGACCTGTCCATTACGGATTTATGGCTAAAAGCGTTTTGCTCTGTAAACAACTGGGGCTGTGTACACAGAGGAAAACGCCTCTGCGGATATACCATGACCCATGAACTGAAAATCCGCGCTCACGTCCCTATTGTATCGCATGCGCCAGGACGTATTTGTTCCCGGGAACCTGGCTTTACTATGTCCTTGATCGAGGACACGTTAAATTTCAAGTTCGCAGGGTGGTGCTGTGTATACCGAAGAAAACGCAAGCTAGGCCAGTTTTAAAATCGTTGTTACCATATCGAACCGTGCCCATACAATTTCTTTACTTATATCGTTACCTTAATTTTAGCGTCGGGATGTCCCAAATCGCGGACCTACTACGTTTAATTGCTTGTAGGGCACACAGTCCTCCAGTTTGTGCGCACATATTGTAGCTACCGCGTCAATATCTACACATAAAAGTGATTGCCGAGTAGGTGGGCTCCTAGCAGATGAGATTAGAGAGGGACTGGGGCCGGTCTGATGCGCTCACAACCATAGTAGACTGCGGAGGCCTTAAATGTACTTGGCCTGGGGATGAATGCGGCTTCTGGTGCAAGGGCATTTATACGAGGACAGTCCAGTTTGATATAACGCGTACATGAGATACAAGTATGTTAAAATGACCTCTAGATGGGGACGACACCTGGGATAACTCCCTCCAATAATATTGCTAACGCTTTAATGGGATAAGTCTCGGAGCGATTCGACTGCATCAAAATCTTCAACTTGGGTCAAAGGTTTAAACCTCCAAGCTCTAAGTCTGTGCGATGTGGGCAATTATCTACGACCAGGTCCCTTAGGACCAAGAAAGAGTAGGGCAAAGGAGCATTCTGAGGCATTCTCTTCGGTGTACACAGCCCCAGAGGATACCACAAGTCATTGTTAGACGACTGATGACATTTTTGTAAACGGCTGGAGTTCGGGGGAGAAAGCGAAGCTGGTCATGGCACTTTTAGTTACCCACGGAAGTGCCAAAACCCAAGGATGGTTGGCGACGCTCCGATGTTCACGCCGTTAACGCGGCCGACGTGAGTTGTGTGGAGGCGAGTG";#"ATGGCCATGGCCCCCAGAACTGAGATCAATAGTACCCGTATTAACGGGTGA";#"AAATTGCTAAATTG" #""#"ATGGCCATGGCC"
#
my $rna = $dna;
$rna =~ tr/Tt/Uu/;
#say $dna;
my $len = length $rna; print length $rna,"n"; #say length $rna;

#Protein of interest
my $interest = "GCEYKEQCF";#"GAVYTEENAS";#"MA";
my $l_interest = length $interest; print length $rna,"\n"; #say $l_interest;


#Initialize variables
my $i;
my $j = 0;
my $f_protein;
my $f_rna_template;			#my @f_protein;
my %f_hash_protein;			#my @f_rna_template;


my $r_protein;
my $r_rna_template;
my %r_hash_protein;					

#Reverse complement
my $rev_com = reverse $dna;
$rev_com =~ tr/ATGCatgc/TACGtacg/;
my $rev_com_rna = $rev_com;
$rev_com_rna =~ tr/Tt/Uu/;




					#my @f_all_proteins;


while($j <= ($len-3)){										# $j = 0 <= (6-3)-1 => 0 <= 2 => 0, 1, 2 => till 3rd position for a 6 letter string
	$i = $j;#say "J =$i";
	
	$f_protein = "";		#CORRECT POSITION FOR RESETTING
	$f_rna_template = "";		#CORRECT POSITION FOR RESETTING
	
	$r_protein = "";
	$r_rna_template = "";
	
	while ($i <= ($len-3)){		#6-3 = 3 => 0, 1, 2, 3
					#say "i = $i";
		
		my $f_substr = substr $rna, $i, 3; 
		$f_protein .= RNA2aa($f_substr);
		$f_rna_template .= $f_substr;
		$f_rna_template =~ tr/Uu/Tt/;
		
		my $r_substr = substr $rev_com_rna, $i, 3; 					#say "Substr: $substr2";
		$r_protein .= RNA2aa($r_substr);
		$r_rna_template .= $r_substr;
		$r_rna_template =~ tr/Uu/Tt/;
		
		
														#say $rna_template;
														#push @f_all_proteins, $f_protein;
		if (length $f_protein == $l_interest){	
														#unless ($protein ne 'MA'){
			push @{$f_hash_protein{$f_protein}}, $f_rna_template if $f_protein eq $interest;											#unless (length $protein != '2'){	
			
														#push @f_protein, $f_protein ;
														#push @f_rna_template,$f_rna_template; #if $protein eq 'MA';
		
			
		}elsif (length $r_protein == $l_interest){
			
		push @{$r_hash_protein{$r_protein}}, $r_rna_template if $r_protein eq $interest;
		
		}																#$protein = "";
																		#$rna_template = "";
		$i = $i+3;								#0+3 = 3 => 0, 1, 2, 3 => 4th position			# if ($protein eq 'MA'){	
	}
	
	$j++;
		
}
	
	
				
		

	
		

#Output
open OUT, ">Output_Peptide_Encoding_code2_2.out" or die $!;

foreach (keys %f_hash_protein){
	#say "$_\t@{$f_hash_protein{$_}}";
	print OUT join ("\t",@{$f_hash_protein{$_}}) if $_ eq $interest;
}
		
		
		
		
			
											# $rna_template = "";
											# }
	

#say "@protein";
#say "@rna_template";
#say "@f_all_proteins"; 
#print "\n\n";




#########################################
#Reverse Complement Computation
#########################################
#say "\n\n################\t\tREVERSE COMPLEMENT\t\t###########################";

#Reverse complement
# my $rev_com = reverse $dna;
# $rev_com =~ tr/ATGCatgc/TACGtacg/;
# my $rev_com_rna = $rev_com;
# $rev_com_rna =~ tr/Tt/Uu/;
#say $rev_com_rna;


# my $k;
# my $l = 0;
# my $r_protein;
# my $r_rna_template;											#my @r_protein;
# my %r_hash_protein;											#my @r_rna_template;



												#my @r_all_proteins;



# while($l <= ($len-3)){										# $j = 0 <= (6-3)-1 => 0 <= 2 => 0, 1, 2 => till 3rd position for a 6 letter string
	# $k = $l;										#say "L =$k";
	
	# $r_protein = "";									#CORRECT POSITION FOR RESETTING
	# $r_rna_template = "";									#CORRECT POSITION FOR RESETTING
	# while ($k <= ($len-3)){									#6-3 = 3 => 0, 1, 2, 3
												# #say "K = $k";
												# #say $rev_com_rna;
		# my $substr2 = substr $rev_com_rna, $k, 3; 					#say "Substr: $substr2";
		# $r_protein .= RNA2aa($substr2);
		# $r_rna_template .= $substr2;
		# $r_rna_template =~ tr/Uu/Tt/;
														# #say $rna_template;
														# #push @r_all_proteins, $r_protein;
		# if (length $r_protein == $l_interest){	
														# #unless ($protein ne 'MA'){
														# #unless (length $protein != '2'){	
			# push @{$r_hash_protein{$r_protein}}, $r_rna_template if $r_protein eq $interest;		
														# #push @r_protein, $r_protein ;
														# #push @r_rna_template,$r_rna_template; #if $protein eq 'MA';
		# }		
	# $k = $k+3;
	
	# }
	
	# $l++;
# }	
		
															#$protein = "";
															#$rna_template = "";
			
#Output
foreach (keys %r_hash_protein){
	#say "$_\t@{$r_hash_protein{$_}}";
	
	foreach my $key( @{$r_hash_protein{$_}} )	{
		
		my $original_sequence = reverse $key;
		$original_sequence =~ tr/ATGCatgc/TACGtacg/;
		print OUT "\t$original_sequence" if $_ eq $interest;
	}
	
}
			

		
		
																#0+3 = 3 => 0, 1, 2, 3 => 4th position			# if ($protein eq 'MA'){
			
																# $rna_template = "";
																# }
	

																#say "@protein";
																#say "@rna_template";
																#say "@r_all_proteins"; 
																#print "\n\n";








#################
#Subroutine
#################

sub RNA2aa{	
	
	my($codon) = @_;
	
	my(%gene_code) = (
	
	'AAA'  => 'K' ,
	'AAC'  => 'N' ,
	'AAG'  => 'K' ,
	'AAU'  => 'N' ,
	'ACA'  => 'T' ,
	'ACC'  => 'T' ,
	'ACG'  => ' T' ,
	'ACU'  => ' T' ,
	'AGA'   => 'R' ,
	'AGC'   => 'S' ,
	'AGG'   => 'R' ,
	'AGU'   => 'S' ,
	'AUA'   => 'I' ,
	'AUC'   => 'I' ,
	'AUG'   => 'M' ,
	'AUU'   => 'I' ,
	'CAA'   => 'Q' ,
	'CAC'   => 'H' ,
	'CAG'   => 'Q' ,
	'CAU'   => 'H' ,
	'CCA'   => 'P' ,
	'CCC'   => 'P' ,
	'CCG'   => 'P' ,
	'CCU'   => 'P' ,
	'CGA'   => 'R' ,
	'CGC'   => 'R' ,
	'CGG'   => 'R' ,
	'CGU'   => 'R' ,
	'CUA'   => 'L' ,
	'CUC'   => 'L' ,
	'CUG'   => 'L' ,
	'CUU'   => 'L' ,
	'GAA'   => 'E' ,
	'GAC'   => 'D' ,
	'GAG'   => 'E' ,
	'GAU'   => 'D' ,
	'GCA'   => 'A' ,
	'GCC'   => 'A' ,
	'GCG'   => 'A' ,
	'GCU'   => 'A' ,
	'GGA'   => 'G' ,
	'GGC'   => 'G' ,
	'GGG'   => 'G' ,
	'GGU'   => 'G' ,
	'GUA'   => 'V' ,
	'GUC'   => 'V' ,
	'GUG'   => 'V' ,
	'GUU'   => 'V' ,
	'UAA'   => 'X',
	'UAC'   => 'Y' ,
	'UAG'   => 'X' ,
	'UAU'   => 'Y' ,
	'UCA'   => 'S' ,
	'UCC'   => 'S' ,
	'UCG'   => 'S' ,
	'UCU'   => 'S' ,
	'UGA'   => 'X' ,
	'UGC'   => 'C' ,
	'UGG'   => 'W' ,
	'UGU'   => 'C' ,
	'UUA'   => 'L' ,
	'UUC'   => 'F' ,
	'UUG'   => 'L' ,
	'UUU'   => 'F' ,
	);

	if (exists $gene_code{$codon} ) {
		return $gene_code{$codon};
		}
		
}
